### ISSUE TITLE
Node Page: Improve Commands, Navigation & Information 

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1067]
Mentioned in #996 we are planning to improve the naviagtion and information density you can receive on the Node page

For reference 
![image](https://user-images.githubusercontent.com/82385103/217822169-0a0db701-a3ef-4412-bafe-cf1240a9d541.png)

----

For this we will add
- [x] an element - showing the status of services

Category | Look (Example) | Element 1# | Element 2#
--- | --- | --- | ---
Execution Clients | ![Gruppe 151](https://user-images.githubusercontent.com/82385103/217943877-35410e8b-faae-4cb5-b843-50cfc7bea938.png) | - Status: Online (green) / Offline (red) / Problem (orange) | - SyncStatus: Synced (green) / Syncing (blue) / Error (red) 
Consensus Clients | ![Lighthouse](https://user-images.githubusercontent.com/82385103/217944907-359e1b79-1f9a-40c6-a11b-bd862aabdd44.png) | - Status: Online (green) / Offline (red) / Problem (orange) |   - SyncStatus: Synced (green) / Syncing (blue) / Error (red) 
Validator Clients | ![Lighthouse Validator Client](https://user-images.githubusercontent.com/82385103/219450516-a8dbdeb9-0166-4d1b-aea9-385bc2f70b4d.png) | - Status: Online (green) / Offline (red) / Problem (orange)  | Imported Keys: [Number of imported keys]
Services | ![Prometheus](https://user-images.githubusercontent.com/82385103/217945670-2bdf305a-1c03-45d2-8c43-52943a639b8e.png) | - Status: Online (green) / Offline (red) / Problem (orange) |

----

- [x] an additional button start/stop individual clients

![image](https://user-images.githubusercontent.com/82385103/217936508-ecdf71bf-3712-4f79-8c67-91fb8f028087.png)

![start-stop](https://user-images.githubusercontent.com/82385103/217936273-95af5b71-1d05-46d7-a8bc-3b0c61960fca.png)

----

- [x] #996 - a button to restart individual clients

----

- [x] #1042 - an additional button to enter the logs

**Comment by daGscheid** [comment]
@MaxTheGeeek & I are working on the following changes for the Node Page & Edit Node Page U.I., raising the information density and improvinge the layout. 

- [ ] "Node Page" Changes

![log changes – 8](https://user-images.githubusercontent.com/82385103/222958024-268c609c-9cdb-4eaa-af87-bbe9ffebfa42.png)

Using the 
![image](https://user-images.githubusercontent.com/82385103/222958169-62955e41-bf67-495c-b275-db601aa4603b.png)
symbol

![log changes – 9](https://user-images.githubusercontent.com/82385103/222958026-8b4d5739-c928-4360-b7e0-c36377dad843.png)

---

- [ ] "Edit Node Page" Changes 

![nuke node button – 2](https://user-images.githubusercontent.com/82385103/222958054-6a81d00f-2396-4544-b962-3c6357f4d6bf.png)

![nuke node button – 4](https://user-images.githubusercontent.com/82385103/222958053-5fff120e-00dc-4335-8806-8ecebaf2d548.png)


- [ ] The layout first of all lets us remove the right click function (wuhu) for deletion (and replace it with the buttons)
- [ ] The selection area for the clients/services should be limited to their icons
----

- [ ] Additional adding the RESYNC Command to the left bar (with #900 being finalized)

![image](https://user-images.githubusercontent.com/82385103/222958203-29dcfb5e-d516-49a4-8b97-f923d3ea97c6.png)

**Comment by stefa2k** [comment]
I think a restart button is more imporant to have than a turn on/off button. Most of the times I want to change the config and just restart, not turn it off and leave it off.

**Comment by daGscheid** [comment]
> I think a restart button is more imporant to have than a turn on/off button. Most of the times I want to change the config and just restart, not turn it off and leave it off.

Aye, aye, we will let the restart button have the place of the start and stop button

**Comment by daGscheid** [comment]
Completed with #1347
