### ISSUE TITLE
[Improvement] Refactor Control Page 

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1712]
### Contact Details

daGscheid

### Describe the problem you ran into!

The current control page was originally just meant as quick path to look up stats, however we and a lot of other users quickly learned to rely on it. 
For this reason. we decided to work on a small rework for the control page improving its codebase, layout, data collection & hopefully getting to add new components. 

### Attach a Screenshot!

![CONTROL PAGE – 5](https://github.com/user-attachments/assets/25ec14a9-0ee6-447d-ba2c-6942584befc4)
![CONTROL PAGE – 7](https://github.com/user-attachments/assets/e08ed314-c8ee-4877-ad90-215b5145f7ea)

### Suggestion Box for Improvement

- [x] New Code Format, Component Layout, with help of @MaxTheGeeek 
- [ ] Changing the layout, removing some components from the page freeing up space
- [ ] Improving existing components to be more clear and easier to use
- [x] Addressing #1654 
- [x] Addressing problems with #1554 
- [x] Addressing #1527, by being able to switch through the client pairs easier
- [ ] Adding new components like #1414
- [ ] Handle Restrictions for Setups better (show left state without Setup installed)

### Launcher Version

2.0.3

### Desktop OS

Windows

### Node Server OS

Ubuntu 22.04

### Acknowledgment

- [X] I looked through the existing issues of this project
