### ISSUE TITLE
Stereum - UI Responsiveness, UX & QoL - Pre/Post 2.0.0 Release - Tracking

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#861]
Currently Stereum is fixed to a certain window size. 
**Not being our top priority,** we made the decision to keep it that way for now, however I would like to open this issue to track usability problems & issues with this. 

I will update it accordingly & include issues related to responsiveness, UX and QoL problems, that should be included in the fixes in the first milestone after full release

- [x] #731 
- [x] #930
- [x] #676 

We are currently discussing how we handle responsiveness improvements & will make this a topic after the 2.0 full release and try tackling as many beforehand as we can. 
Please feel free to include any minor annoyances with the UI in this issue.

## QoL
- [x] Taskmanager Improvments 
     - [x] Show "Skipped" Tasks in Task Manager as in "Grey" Color instead of sharing color with Active
     - [x] #1440 

## Minor
- [x] Add a dumb clicker game with highscore to the Nuke Node Modal (I love clicking the deactivated button - dk why, but I think it would be fun)

**Comment by daGscheid** [comment]
Small Bugfixes to do with new UI:

----

- [ ] Either Remove or Throw a text proompting the user the login @MaxTheGeeek - 
             -> "You have to login to access server management"


https://github.com/stereum-dev/ethereum-node/assets/82385103/6e373b46-4d85-4cb0-a569-8a8afec0953a


---

- [ ] Remove Export Node Config in Settings @mabasian 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/fa11d895-202a-4ca1-8e5a-c9a43b9429c4)

---

- [ ] Could you make this distance a little more on the control page @mabasian  (looks cool btw)

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/4de17668-dd5a-4da0-88d7-35e44bd1b963)

**Comment by stefa2k** [comment]
sync status display on görli doesn't work
![image](https://github.com/stereum-dev/ethereum-node/assets/54934211/46ad7237-450b-4c49-bd14-96f120a5feb1)

**Comment by NeoPlays** [comment]
> * [ ]  sync status display on görli doesn't work
>       ![image](https://user-images.githubusercontent.com/54934211/279049333-46ad7237-450b-4c49-bd14-96f120a5feb1.png)

The Sync status uses the same data as on Control Page and should work (works on my machine 😅 ). You may need to resatart Prometheus.

**Comment by daGscheid** [comment]
Thanks for the big review yesterday guys 🙏

**Comment by daGscheid** [comment]
- [ ] Negative Rewards in Modal should be shown in red please @mabasian 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/84f81b28-436e-4f9e-9a4d-a7108b873034)

**Comment by daGscheid** [comment]
Continued in #1601
